version: '3'

services:
  scrape404:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    volumes:
      - ./results:/home/appuser/results